Imports Coding4Fun.Toolkit
Imports Coding4Fun.Toolkit.Controls
Imports Coding4Fun.Toolkit.Controls.InputPrompt
Imports System.Windows.Input
Imports Coding4Fun.Toolkit.Controls.UserPrompt
Partial Public Class PageMoves
    Inherits PhoneApplicationPage

    Public Sub New()
        InitializeComponent()
    End Sub
    Private Sub ApplicationBarIconButton_Click(sender As Object, e As EventArgs)
        Dim InputBoxEx As InputPrompt
        InputBoxEx = New InputPrompt
        Dim InputScopeNumber As InputScope
        InputScopeNumber = New InputScope
        Dim InputScopeNumberName As InputScopeName
        InputScopeNumberName = New InputScopeName
        With InputScopeNumberName
            .NameValue = InputScopeNameValue.Number
        End With
        With InputScopeNumber
            .Names.Add(InputScopeNumberName)
        End With
        With InputBoxEx
            AddHandler .Completed, AddressOf InputPrompt_Completed
            .Title = "定位到編號"
            .Message = "請輸入您需要的技能的編號。" & vbCrLf & "範圍: 001-" & lstMoves.Items.Count
            .InputScope = InputScopeNumber
            .Show()
        End With
    End Sub

    Private Sub ApplicationBarIconButton_Click_1(sender As Object, e As EventArgs)
        Dim InputBoxEx As InputPrompt
        InputBoxEx = New InputPrompt
        If 245 = 25 Then
            Dim InputScopeNumber As InputScope
            InputScopeNumber = New InputScope
            Dim InputScopeNumberName As InputScopeName
            InputScopeNumberName = New InputScopeName
            With InputScopeNumberName
                .NameValue = InputScopeNameValue.Search
            End With
            With InputScopeNumber
                .Names.Add(InputScopeNumberName)
            End With
        End If
        Dim InputScopeSearch As InputScope
        InputScopeSearch = New InputScope
        Dim InputScopeSearchName As InputScopeName
        InputScopeSearchName = New InputScopeName
        With InputScopeSearchName
            .NameValue = InputScopeNameValue.Search
        End With
        With InputScopeSearch
            .Names.Add(InputScopeSearchName)
        End With
        With InputBoxEx
            AddHandler .Completed, AddressOf SearchRequest_Completed
            .Title = "搜尋"
            .InputScope = InputScopeSearch
            .Message = "請輸入您需要的技能名稱的全部或者部分內容。"
            .Show()
        End With
    End Sub
    Sub InputPrompt_Completed(lpSender As Object, e As PopUpEventArgs(Of String, PopUpResult))
        If e.PopUpResult = PopUpResult.Ok Then
            Dim lpNum As String
            Dim lpNumInt As Long
            lpNum = e.Result
            If IsNumber(lpNum) = 0 Then
                MessageBox.Show("請輸入有效的數值。", "錯誤", MessageBoxButton.OK)
                Exit Sub
            End If
            lpNumInt = CLng(lpNum)
            If (1 <= lpNumInt) And (lpNumInt <= lstMoves.Items.Count) Then
                lstMoves.SelectedIndex = lpNumInt - 1
            Else
                MessageBox.Show("輸入的編號超出允許的範圍。", "錯誤", MessageBoxButton.OK)
                Exit Sub
            End If
            'MessageBox.Show(Me.lstPokemons.SelectedItems.Item(0))
        Else
            Exit Sub
        End If
    End Sub
    Sub SearchRequest_Completed(lpSender As Object, e As PopUpEventArgs(Of String, PopUpResult))
        If 25 = 245 Then
            If e.PopUpResult = PopUpResult.Ok Then
                Dim lpNum As String
                Dim lpNumInt As Long
                lpNum = e.Result
                lpNumInt = CLng(lpNum)
                If (1 <= lpNumInt) And (lpNumInt <= 721) Then
                    lstMoves.SelectedIndex = lpNumInt - 1
                Else
                    MessageBox.Show("輸入的編號超出允許的範圍。", "錯誤", MessageBoxButton.OK)
                    Exit Sub
                End If
                'MessageBox.Show(Me.lstPokemons.SelectedItems.Item(0))
                Dim imgSelPkMn As Media.Imaging.BitmapImage
                imgSelPkMn = New Imaging.BitmapImage
                Dim strSel As String
                strSel = lstMoves.SelectedItems.Item(0).ToString
                strSel = strSel.Chars(0) & strSel.Chars(1) & strSel.Chars(2)
                If 25 = 245 Then
                    MessageBox.Show(strSel)
                End If
                imgSelPkMn.UriSource = New Uri("/PokemonsL/" & strSel & ".png", UriKind.RelativeOrAbsolute)
                'imgPokemon.Source = imgSelPkMn

            Else
                Exit Sub
            End If
        End If
        If e.PopUpResult = PopUpResult.Ok Then
            Dim lpIPBSearchRequest As String
            lpIPBSearchRequest = e.Result.Trim
            If lpIPBSearchRequest = "" Then
                MessageBox.Show("請不要嘗試搜尋空白內容或者純空白字符。", "錯誤", MessageBoxButton.OK)
                Exit Sub
            End If
            lpSearchRequest = lpIPBSearchRequest
            'NavigationService
            NavigationService.Navigate(New Uri("/PageMoveSearch.xaml", UriKind.RelativeOrAbsolute))
        Else
            Exit Sub
        End If
    End Sub

    Private Sub PageMoves_Loaded(sender As Object, e As RoutedEventArgs) Handles Me.Loaded
        Select Case UIMovesChineseDisplayConfig
            Case ChineseDisplayConfig.DefaultConfig
                lstMoves.ItemsSource = ListMovesCHT_Official
            Case ChineseDisplayConfig.InformalChineseSimplified
                lstMoves.ItemsSource = ListMovesCHS
            Case ChineseDisplayConfig.InformalChineseTraditional
                lstMoves.ItemsSource = ListMovesCHT
            Case ChineseDisplayConfig.OfficialChineseSimplified
                lstMoves.ItemsSource = ListMovesCHS_Official
            Case ChineseDisplayConfig.OfficialChineseTraditional
                lstMoves.ItemsSource = ListMovesCHT_Official
        End Select
        Exit Sub
        'InitializeMoveInformation()
        Dim lstMoveSource As New List(Of String)
        With lstMoveSource
            .Add("001 拍擊")
            .Add("002 手刀")
            .Add("003 連環巴掌")
            .Add("004 連續拳")
            .Add("005 百萬噸拳擊")
            .Add("006 聚寶功")
            .Add("007 火焰拳")
            .Add("008 急凍拳")
            .Add("009 雷光掌")
            .Add("010 利爪")
            .Add("011 剪斷")
            .Add("012 剪刀斷頭臺")
            .Add("013 旋風刀")
            .Add("014 劍舞")
            .Add("015 一字斬")
            .Add("016 烈暴風")
            .Add("017 翅膀攻擊")
            .Add("018 旋風")
            .Add("019 飛翔")
            .Add("020 綁緊")
            .Add("021 叩打")
            .Add("022 藤鞭")
            .Add("023 踐踏")
            .Add("024 連環腿")
            .Add("025 百萬噸飛腿")
            .Add("026 飛踢")
            .Add("027 旋風腿")
            .Add("028 飛沙腳")
            .Add("029 鐵頭功")
            .Add("030 角撞")
            .Add("031 瘋狂攻擊")
            .Add("032 獨角鑽")
            .Add("033 衝擊")
            .Add("034 泰山壓頂")
            .Add("035 捆綁")
            .Add("036 猛撞")
            .Add("037 橫衝直撞")
            .Add("038 捨身攻擊")
            .Add("039 搖尾巴")
            .Add("040 毒針")
            .Add("041 雙針")
            .Add("042 飛彈針")
            .Add("043 瞪眼")
            .Add("044 咬咬")
            .Add("045 嚎叫")
            .Add("046 吼叫")
            .Add("047 唱歌")
            .Add("048 超音波")
            .Add("049 音爆")
            .Add("050 石化功")
            .Add("051 溶解液")
            .Add("052 火花")
            .Add("053 噴射火焰")
            .Add("054 白霧")
            .Add("055 水槍")
            .Add("056 水炮")
            .Add("057 衝浪")
            .Add("058 急凍光線")
            .Add("059 暴風雪")
            .Add("060 幻象光")
            .Add("061 泡沫光線")
            .Add("062 極光束")
            .Add("063 破壞死光")
            .Add("064 啄")
            .Add("065 衝鑽")
            .Add("066 地獄滾動")
            .Add("067 下踢")
            .Add("068 返拳")
            .Add("069 地球上投")
            .Add("070 勁力")
            .Add("071 吸收")
            .Add("072 百萬噸吸收")
            .Add("073 寄生種子")
            .Add("074 生長")
            .Add("075 飛葉快刀")
            .Add("076 陽光烈焰")
            .Add("077 毒粉末")
            .Add("078 麻痺粉")
            .Add("079 睡眠粉")
            .Add("080 花之舞")
            .Add("081 吐絲")
            .Add("082 龍之怒")
            .Add("083 火焰漩渦")
            .Add("084 電擊")
            .Add("085 十萬伏特")
            .Add("086 電磁波")
            .Add("087 打雷")
            .Add("088 滾石")
            .Add("089 地震")
            .Add("090 地裂")
            .Add("091 挖地洞")
            .Add("092 猛毒素")
            .Add("093 念力")
            .Add("094 幻象術")
            .Add("095 催眠術")
            .Add("096 瑜伽姿勢")
            .Add("097 高速移動")
            .Add("098 電光一閃")
            .Add("099 憤怒")
            .Add("100 瞬間移動")
            .Add("101 黑夜詛咒")
            .Add("102 模仿")
            .Add("103 噪音")
            .Add("104 影子分身")
            .Add("105 自我復原")
            .Add("106 硬梆梆")
            .Add("107 縮小")
            .Add("108 煙幕")
            .Add("109 奇異光線")
            .Add("110 縮殼")
            .Add("111 防衛卷")
            .Add("112 障礙")
            .Add("113 光牆")
            .Add("114 黑霧")
            .Add("115 減半反射")
            .Add("116 集氣")
            .Add("117 忍忍")
            .Add("118 揮指功")
            .Add("119 學舌術")
            .Add("120 自爆")
            .Add("121 炸蛋")
            .Add("122 舔舌頭")
            .Add("123 迷霧")
            .Add("124 泥漿攻擊")
            .Add("125 骨棒")
            .Add("126 大字爆")
            .Add("127 魚躍龍門")
            .Add("128 夾殼")
            .Add("129 高速星星")
            .Add("130 火箭頭槌")
            .Add("131 尖刺加農炮")
            .Add("132 糾纏")
            .Add("133 瞬間失憶")
            .Add("134 折彎湯匙")
            .Add("135 生蛋")
            .Add("136 飛膝撞")
            .Add("137 大蛇瞪眼")
            .Add("138 食夢")
            .Add("139 毒瓦斯")
            .Add("140 丟球")
            .Add("141 吸血")
            .Add("142 惡魔之吻")
            .Add("143 高空攻擊")
            .Add("144 變身")
            .Add("145 泡沫")
            .Add("146 迷昏拳")
            .Add("147 蘑菇孢子")
            .Add("148 閃光")
            .Add("149 幻象波")
            .Add("150 水濺躍")
            .Add("151 溶化")
            .Add("152 螃蟹拳")
            .Add("153 大爆炸")
            .Add("154 瘋狂亂抓")
            .Add("155 骨頭回力鏢")
            .Add("156 睡覺")
            .Add("157 山崩地裂")
            .Add("158 必殺門牙")
            .Add("159 稜角")
            .Add("160 變性")
            .Add("161 三角攻擊")
            .Add("162 憤怒之牙")
            .Add("163 劈開")
            .Add("164 替身")
            .Add("165 掙扎")
            .Add("166 寫生")
            .Add("167 三倍足攻")
            .Add("168 小偷")
            .Add("169 蛛絲")
            .Add("170 心眼")
            .Add("171 惡夢")
            .Add("172 火焰輪")
            .Add("173 打鼾")
            .Add("174 咒語")
            .Add("175 手足慌亂")
            .Add("176 變性II")
            .Add("177 空氣爆炸")
            .Add("178 棉孢子")
            .Add("179 起死回生")
            .Add("180 痛恨")
            .Add("181 細雪")
            .Add("182 守住")
            .Add("183 音速拳")
            .Add("184 鬼臉")
            .Add("185 虛晃一招")
            .Add("186 天使之吻")
            .Add("187 肚子大鼓")
            .Add("188 臭泥爆彈")
            .Add("189 泥湯")
            .Add("190 章魚桶炮")
            .Add("191 滿地星")
            .Add("192 電磁炮")
            .Add("193 看破")
            .Add("194 同命")
            .Add("195 滅亡之歌")
            .Add("196 凍風")
            .Add("197 先決")
            .Add("198 骨擊一氣")
            .Add("199 鎖定")
            .Add("200 龍鱗之怒")
            .Add("201 沙雹")
            .Add("202 超級吸收")
            .Add("203 忍耐")
            .Add("204 撒嬌")
            .Add("205 滾動")
            .Add("206 刀背擊打")
            .Add("207 裝腔作勢")
            .Add("208 飲奶")
            .Add("209 閃電")
            .Add("210 連切")
            .Add("211 鋼翼")
            .Add("212 黑色眼光")
            .Add("213 迷人")
            .Add("214 夢話")
            .Add("215 治癒鈴聲")
            .Add("216 報恩")
            .Add("217 禮物")
            .Add("218 牽連")
            .Add("219 神秘護身")
            .Add("220 分享痛楚")
            .Add("221 聖之火")
            .Add("222 震級")
            .Add("223 爆裂拳")
            .Add("224 百萬噸角擊")
            .Add("225 龍吸")
            .Add("226 接棒")
            .Add("227 再來一次")
            .Add("228 追打")
            .Add("229 高速迴轉")
            .Add("230 甜氣")
            .Add("231 鐵尾")
            .Add("232 合金爪")
            .Add("233 一招制敵")
            .Add("234 晨光")
            .Add("235 光學合成")
            .Add("236 月光")
            .Add("237 催醒")
            .Add("238 十字切")
            .Add("239 龍捲風")
            .Add("240 乞雨")
            .Add("241 大晴天")
            .Add("242 咬碎")
            .Add("243 表面塗層")
            .Add("244 自我暗示")
            .Add("245 神速")
            .Add("246 原始之力")
            .Add("247 影子球")
            .Add("248 先知")
            .Add("249 岩石粉碎")
            .Add("250 潮旋")
            .Add("251 痛打一氣")
            .Add("252 假動作")
            .Add("253 吵鬧")
            .Add("254 儲存")
            .Add("255 噴出")
            .Add("256 吞下")
            .Add("257 熱風")
            .Add("258 冰雹")
            .Add("259 假指控")
            .Add("260 煽惑")
            .Add("261 鬼火")
            .Add("262 臨別禮物")
            .Add("263 假勇敢")
            .Add("264 集中猛擊")
            .Add("265 甦醒")
            .Add("266 跟我來")
            .Add("267 自然能力")
            .Add("268 充電")
            .Add("269 挑撥")
            .Add("270 幫助")
            .Add("271 騙術")
            .Add("272 角色扮演")
            .Add("273 祈求")
            .Add("274 協助")
            .Add("275 根深蒂固")
            .Add("276 蠻力")
            .Add("277 魔術外衣")
            .Add("278 回收")
            .Add("279 報仇")
            .Add("280 劈瓦")
            .Add("281 哈欠")
            .Add("282 落拳")
            .Add("283 強攻")
            .Add("284 噴火")
            .Add("285 交換絕招")
            .Add("286 封印")
            .Add("287 清新")
            .Add("288 怨恨")
            .Add("289 搶奪")
            .Add("290 神秘力量")
            .Add("291 潛水")
            .Add("292 猛推")
            .Add("293 保護色")
            .Add("294 螢火")
            .Add("295 潔淨光澤")
            .Add("296 薄霧球")
            .Add("297 羽毛舞")
            .Add("298 搖晃舞")
            .Add("299 火焰踢")
            .Add("300 玩泥巴")
            .Add("301 冰球")
            .Add("302 針葉暗器")
            .Add("303 懶惰")
            .Add("304 高音")
            .Add("305 毒液牙")
            .Add("306 突擊爪")
            .Add("307 爆炸燃燒")
            .Add("308 水電炮")
            .Add("309 流星拳")
            .Add("310 驚嚇")
            .Add("311 氣象球")
            .Add("312 芳香治療")
            .Add("313 假哭")
            .Add("314 破空斬")
            .Add("315 過熱")
            .Add("316 氣味偵測")
            .Add("317 岩石封閉")
            .Add("318 銀色旋風")
            .Add("319 金屬音")
            .Add("320 草笛魔音")
            .Add("321 搔癢")
            .Add("322 無限能量")
            .Add("323 噴水")
            .Add("324 信號光束")
            .Add("325 影子拳")
            .Add("326 神通力")
            .Add("327 上天拳")
            .Add("328 流沙地獄")
            .Add("329 絕對零度")
            .Add("330 濁流")
            .Add("331 種子機關槍")
            .Add("332 迴轉攻")
            .Add("333 冰針")
            .Add("334 鐵壁")
            .Add("335 擋路")
            .Add("336 長嚎")
            .Add("337 龍爪")
            .Add("338 瘋狂機器")
            .Add("339 健美")
            .Add("340 飛跳")
            .Add("341 泥巴射擊")
            .Add("342 毒尾")
            .Add("343 渴望")
            .Add("344 伏特攻擊")
            .Add("345 魔法葉")
            .Add("346 水之遊")
            .Add("347 冥想")
            .Add("348 刀葉")
            .Add("349 龍之舞")
            .Add("350 岩石爆破")
            .Add("351 電擊波")
            .Add("352 水波動")
            .Add("353 破滅願望")
            .Add("354 精神提升")
            .Add("355 歇息")
            .Add("356 重力")
            .Add("357 奇蹟眼")
            .Add("358 甦醒巴掌")
            .Add("359 臂力拳")
            .Add("360 迴轉球")
            .Add("361 治癒願望")
            .Add("362 鹽水")
            .Add("363 自然之恩")
            .Add("364 佯攻")
            .Add("365 啄食")
            .Add("366 順風")
            .Add("367 點穴")
            .Add("368 合金爆裂")
            .Add("369 急速轉變")
            .Add("370 近身打")
            .Add("371 報復")
            .Add("372 再三囑咐")
            .Add("373 徵收")
            .Add("374 投擲")
            .Add("375 幻象轉移")
            .Add("376 王牌")
            .Add("377 回復阻擋")
            .Add("378 擰乾")
            .Add("379 能量騙術")
            .Add("380 胃液")
            .Add("381 幸運咒語")
            .Add("382 先搶先贏")
            .Add("383 仿造")
            .Add("384 力量交換")
            .Add("385 防禦交換")
            .Add("386 懲罰")
            .Add("387 珍藏")
            .Add("388 煩惱種子")
            .Add("389 突襲")
            .Add("390 毒尖釘")
            .Add("391 交換意志")
            .Add("392 水柱圈")
            .Add("393 電磁浮遊")
            .Add("394 爆炎電擊")
            .Add("395 發勁")
            .Add("396 波導彈")
            .Add("397 磨光岩石")
            .Add("398 毒刺")
            .Add("399 惡波動")
            .Add("400 街頭試刀")
            .Add("401 水柱尾")
            .Add("402 種子爆彈")
            .Add("403 空氣砍")
            .Add("404 剪刀十字拳")
            .Add("405 蟲鳴")
            .Add("406 龍波動")
            .Add("407 龍神俯衝")
            .Add("408 力量寶石")
            .Add("409 吸收拳")
            .Add("410 真空波")
            .Add("411 集氣彈")
            .Add("412 能源球")
            .Add("413 神鳥特攻")
            .Add("414 大地之力")
            .Add("415 掉包")
            .Add("416 超極衝擊")
            .Add("417 詭計")
            .Add("418 飛彈拳")
            .Add("419 雪崩")
            .Add("420 冰粒")
            .Add("421 影子鉤爪")
            .Add("422 雷牙")
            .Add("423 冰牙")
            .Add("424 炎牙")
            .Add("425 影子偷襲")
            .Add("426 泥巴爆彈")
            .Add("427 幻象斬")
            .Add("428 意念頭錘")
            .Add("429 鏡光射擊")
            .Add("430 光澤電炮")
            .Add("431 攀登岩石")
            .Add("432 清除濃霧")
            .Add("433 騙術空間")
            .Add("434 天龍流星")
            .Add("435 放電")
            .Add("436 噴煙")
            .Add("437 葉暴風")
            .Add("438 能量鞭打")
            .Add("439 岩石炮")
            .Add("440 十字毒藥")
            .Add("441 灰塵射擊")
            .Add("442 鐵頭")
            .Add("443 磁鐵爆彈")
            .Add("444 尖石攻擊")
            .Add("445 誘惑")
            .Add("446 隱形岩")
            .Add("447 打草結")
            .Add("448 喋喋不休")
            .Add("449 制裁石礫")
            .Add("450 蟲咬")
            .Add("451 充電光束")
            .Add("452 木槌")
            .Add("453 噴射水柱")
            .Add("454 攻擊指令")
            .Add("455 防禦指令")
            .Add("456 回復指令")
            .Add("457 雙刃頭錘")
            .Add("458 雙重攻擊")
            .Add("459 時間咆哮")
            .Add("460 隔空切斷")
            .Add("461 新月舞")
            .Add("462 捏碎")
            .Add("463 岩漿暴風")
            .Add("464 黑洞")
            .Add("465 種子閃光")
            .Add("466 奇異之風")
            .Add("467 影子潛水")
            .Add("468 磨爪子")
            .Add("469 全體防禦")
            .Add("470 防禦平分")
            .Add("471 力量平分")
            .Add("472 奇妙空間")
            .Add("473 幻象攻擊")
            .Add("474 毒液攻擊")
            .Add("475 體重減輕")
            .Add("476 憤怒之粉")
            .Add("477 心靈傳動術")
            .Add("478 魔法空間")
            .Add("479 擊落")
            .Add("480 山嵐")
            .Add("481 爆炸火焰")
            .Add("482 泥漿波")
            .Add("483 蝶之舞")
            .Add("484 沉重轟炸")
            .Add("485 同步干擾")
            .Add("486 電球")
            .Add("487 浸水")
            .Add("488 火焰襲擊")
            .Add("489 盤卷")
            .Add("490 低空踢")
            .Add("491 酸液炸彈")
            .Add("492 詐欺")
            .Add("493 單純光線")
            .Add("494 變為同伴")
            .Add("495 你先請")
            .Add("496 輪唱")
            .Add("497 回音")
            .Add("498 循序漸進")
            .Add("499 清除迷霧")
            .Add("500 協助力量")
            .Add("501 先制防禦")
            .Add("502 位置交換")
            .Add("503 熱水")
            .Add("504 破殼")
            .Add("505 治癒波動")
            .Add("506 厄運臨頭")
            .Add("507 自由落體")
            .Add("508 交換齒輪")
            .Add("509 巴投")
            .Add("510 燒盡")
            .Add("511 延後")
            .Add("512 特技演員")
            .Add("513 鏡子系")
            .Add("514 討敵")
            .Add("515 賭命")
            .Add("516 禮物傳遞")
            .Add("517 煉獄")
            .Add("518 水的誓約")
            .Add("519 炎的誓約")
            .Add("520 草的誓約")
            .Add("521 交換伏特")
            .Add("522 蟲的抵抗")
            .Add("523 整地")
            .Add("524 冰吸")
            .Add("525 龍尾")
            .Add("526 自我激勵")
            .Add("527 電網")
            .Add("528 瘋狂伏特")
            .Add("529 低空鑽")
            .Add("530 雙重劈")
            .Add("531 愛心搗擊")
            .Add("532 木角")
            .Add("533 聖劍")
            .Add("534 貝殼刀")
            .Add("535 高溫搗擊")
            .Add("536 青草攪拌器")
            .Add("537 瘋狂滾動")
            .Add("538 棉花防禦")
            .Add("539 黑夜爆裂")
            .Add("540 精神破壞")
            .Add("541 掃巴掌")
            .Add("542 暴風")
            .Add("543 爆爆頭突擊")
            .Add("544 齒輪飛盤")
            .Add("545 火炎彈")
            .Add("546 破壞技術")
            .Add("547 古老之歌")
            .Add("548 神秘之劍")
            .Add("549 冰凍世界")
            .Add("550 雷擊")
            .Add("551 青炎")
            .Add("552 炎之舞")
            .Add("553 凍結伏特")
            .Add("554 寒冷閃光")
            .Add("555 大聲咆哮")
            .Add("556 掉落冰柱")
            .Add("557 勝利V熱炎")
            .Add("558 十字交叉火焰")
            .Add("559 十字交叉閃電")
            .Add("560 飛衝落地")
            .Add("561 墊返")
            .Add("562 打嗝")
            .Add("563 耕地")
            .Add("564 黏黏網")
            .Add("565 擊倒針刺")
            .Add("566 幽靈潛水")
            .Add("567 萬聖夜狂歡")
            .Add("568 戰吼")
            .Add("569 電漿陣雨")
            .Add("570 拋物線充電")
            .Add("571 森林詛咒")
            .Add("572 花瓣暴風雪")
            .Add("573 冰凍乾燥")
            .Add("574 魅惑之音")
            .Add("575 放狠話")
            .Add("576 翻倒")
            .Add("577 吸取之吻")
            .Add("578 狡猾防禦")
            .Add("579 鮮花防禦")
            .Add("580 草原場地")
            .Add("581 薄霧場地")
            .Add("582 送電")
            .Add("583 嬉戲")
            .Add("584 妖精之風")
            .Add("585 月亮攻擊")
            .Add("586 爆音波")
            .Add("587 妖精之鎖")
            .Add("588 王者盾牌")
            .Add("589 做朋友")
            .Add("590 悄悄話")
            .Add("591 鑽石暴風")
            .Add("592 蒸汽噴發")
            .Add("593 異次元蟲洞")
            .Add("594 水手裏劍")
            .Add("595 魔法火焰")
            .Add("596 刺針防禦")
            .Add("597 芳香薄霧")
            .Add("598 怪電波")
            .Add("599 毒液陷阱")
            .Add("600 粉塵")
            .Add("601 大地控制")
            .Add("602 磁場操作")
            .Add("603 快樂時光")
            .Add("604 電氣場地")
            .Add("605 魔法照耀")
            .Add("606 慶祝")
            .Add("607 牽手")
            .Add("608 圓滑目光")
            .Add("609 碰碰臉頰")
            .Add("610 手下留情")
            .Add("611 纏身")
            .Add("612 增強拳")
            .Add("613 死亡之翼")
            .Add("614 萬波激震")
            .Add("615 萬箭齊發")
            .Add("616 大地原力")
            .Add("617 破滅之光")
            .Add("618 根源波動")
            .Add("619 斷崖之劍")
            .Add("620 畫龍點睛")
            .Add("621 異次元衝鋒")
        End With
        lstMoves.ItemsSource = lstMoveSource
    End Sub

    Private Sub lstMoves_DoubleTap(sender As Object, e As GestureEventArgs) Handles lstMoves.DoubleTap
        If lstMoves.SelectedIndex < 0 Or lstMoves.SelectedIndex > lstMoves.Items.Count - 1 Then
            Exit Sub
        End If
        MoveSelectionNumber = lstMoves.SelectedIndex
        NavigationService.Navigate(New Uri("/PageMoveDetails.xaml", UriKind.RelativeOrAbsolute))
    End Sub

    Private Sub lstMoves_Tap(sender As Object, e As GestureEventArgs) Handles lstMoves.Tap
        If lstMoves.SelectedIndex < 0 Then
            Exit Sub
        End If
        MoveSelectionNumber = lstMoves.SelectedIndex
    End Sub
    Private Sub ApplicationBarIconButton_Click_2(sender As Object, e As EventArgs)
        lstMoves.SelectedIndex = 0
    End Sub

    Private Sub ApplicationBarIconButton_Click_3(sender As Object, e As EventArgs)
        lstMoves.SelectedIndex = lstMoves.Items.Count - 1
    End Sub
End Class
